//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cavity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cavity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration section is required..
        /// </summary>
        internal static string ConfiguredList_NullSectionMessage {
            get {
                return ResourceManager.GetString("ConfiguredList_NullSectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entity tag must be enclosed with quotes and may optionally begin with W/..
        /// </summary>
        internal static string EntityTag_FormatException_Message {
            get {
                return ResourceManager.GetString("EntityTag_FormatException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index value of {0} is beyond the length of &quot;{1}&quot;..
        /// </summary>
        internal static string ExceptionMessage_IndexAfterValueLength {
            get {
                return ResourceManager.GetString("ExceptionMessage_IndexAfterValueLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length value of {0} is shorter than the length of the value &quot;{1}&quot;..
        /// </summary>
        internal static string ExceptionMessage_LengthShorterThanValueLength {
            get {
                return ResourceManager.GetString("ExceptionMessage_LengthShorterThanValueLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index value of {0} is negative..
        /// </summary>
        internal static string ExceptionMessage_NegativeIndex {
            get {
                return ResourceManager.GetString("ExceptionMessage_NegativeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length value of {0} is negative..
        /// </summary>
        internal static string ExceptionMessage_NegativeLength {
            get {
                return ResourceManager.GetString("ExceptionMessage_NegativeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value of {0} is negative..
        /// </summary>
        internal static string ExceptionMessage_NegativeStartIndex {
            get {
                return ResourceManager.GetString("ExceptionMessage_NegativeStartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value of {0} is beyond the length of &quot;{1}&quot;..
        /// </summary>
        internal static string ExceptionMessage_StartIndexAfterValueLength {
            get {
                return ResourceManager.GetString("ExceptionMessage_StartIndexAfterValueLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start + length value of {0} + {1} is beyond the length of &quot;{2}&quot;..
        /// </summary>
        internal static string ExceptionMessage_StartIndexAndLengthAfterValueLength {
            get {
                return ResourceManager.GetString("ExceptionMessage_StartIndexAndLengthAfterValueLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than the size of the collection..
        /// </summary>
        internal static string IndexOutOfRangeException_Message {
            get {
                return ResourceManager.GetString("IndexOutOfRangeException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper bound must be greater than the lower bound..
        /// </summary>
        internal static string ObjectExtensionMethods_IsBoundedBy_Message {
            get {
                return ResourceManager.GetString("ObjectExtensionMethods_IsBoundedBy_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A token is restricted to any char except control keys or separators..
        /// </summary>
        internal static string Token_FormatException_Message {
            get {
                return ResourceManager.GetString("Token_FormatException_Message", resourceCulture);
            }
        }
    }
}
