//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhenFresh.Utilities.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WhenFresh.Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConfiguredList_NullSectionMessage {
            get {
                return ResourceManager.GetString("ConfiguredList_NullSectionMessage", resourceCulture);
            }
        }
        
        internal static string EntityTag_FormatException_Message {
            get {
                return ResourceManager.GetString("EntityTag_FormatException_Message", resourceCulture);
            }
        }
        
        internal static string ExceptionMessage_IndexAfterValueLength {
            get {
                return ResourceManager.GetString("ExceptionMessage_IndexAfterValueLength", resourceCulture);
            }
        }
        
        internal static string ExceptionMessage_LengthShorterThanValueLength {
            get {
                return ResourceManager.GetString("ExceptionMessage_LengthShorterThanValueLength", resourceCulture);
            }
        }
        
        internal static string ExceptionMessage_NegativeIndex {
            get {
                return ResourceManager.GetString("ExceptionMessage_NegativeIndex", resourceCulture);
            }
        }
        
        internal static string ExceptionMessage_NegativeLength {
            get {
                return ResourceManager.GetString("ExceptionMessage_NegativeLength", resourceCulture);
            }
        }
        
        internal static string ExceptionMessage_NegativeStartIndex {
            get {
                return ResourceManager.GetString("ExceptionMessage_NegativeStartIndex", resourceCulture);
            }
        }
        
        internal static string ExceptionMessage_StartIndexAfterValueLength {
            get {
                return ResourceManager.GetString("ExceptionMessage_StartIndexAfterValueLength", resourceCulture);
            }
        }
        
        internal static string ExceptionMessage_StartIndexAndLengthAfterValueLength {
            get {
                return ResourceManager.GetString("ExceptionMessage_StartIndexAndLengthAfterValueLength", resourceCulture);
            }
        }
        
        internal static string IndexOutOfRangeException_Message {
            get {
                return ResourceManager.GetString("IndexOutOfRangeException_Message", resourceCulture);
            }
        }
        
        internal static string ObjectExtensionMethods_IsBoundedBy_Message {
            get {
                return ResourceManager.GetString("ObjectExtensionMethods_IsBoundedBy_Message", resourceCulture);
            }
        }
        
        internal static string Token_FormatException_Message {
            get {
                return ResourceManager.GetString("Token_FormatException_Message", resourceCulture);
            }
        }
    }
}
